language: go

go:
  - "1.11.x"

before_script:
  - go get -u github.com/mitchellh/gox
  - go vet github.com/martindelille/dbxcli

install: true

script:
  - ./build.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file_glob: true
  file: "dist/*"
  on:
    tags: true
